# Generated by Django 5.2.14 on 2026-06-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cliente_ativo_alter_agendamento_id_alter_cliente_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='especie',
            field=models.CharField(choices=[('CACHORRO', 'Cachorro'), ('GATO', 'Gato'), ('PASSARO', 'Pássaro'), ('COELHO', 'Coelho'), ('HAMSTER', 'Hamster'), ('OUTRO', 'Outro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pet',
            name='porte',
            field=models.CharField(choices=[('PEQUENO', 'Pequeno Porte'), ('MEDIO', 'Médio Porte'), ('GRANDE', 'Grande Porte')], max_length=20),
        ),
    ]
